### PR TITLE
Fix for issue 363

### PR DESCRIPTION
**Pull request by paranojk**
Config was missing schema, so it was propagating to container as empty. Adding schema fixed the bug.

### CODE REVIEW

**Comment by carldebilly** [comment]
Thanks for this PR!
There's more available settings than just thost... but it's better than nothing.

**Comment by Pawel128** [comment]
I also have this problem. I believe that your solution is very good, but I don't know how to apply it, what to do with the config.json file? put it somewhere? please give me a hint, thank you

**Comment by carldebilly** [comment]
I'll push a new version later today.

**Comment by PiotrBielecki** [comment]
@carldebilly can you please help with this? :)

**Pull request merged**
